spring:
  application:
    name: employee-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emp_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}

jwt:
  secret: mySuperSecretKeyForJwtTokenGeneration123456
  expiration: 86400000