spring:
  application:
    name: employee-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 0   # prevents crash if DB delay

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT}

jwt:
  secret: mySuperSecretKeyForJwtTokenGeneration123456
  expiration: 86400000