spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:postgresql://dpg-d6vd9h95pdvs738j9gvg-a.singapore-postgres.render.com:5432/employee_management_0gfi
    username: admin
    password: b48OhxXvmFRbNU68IUu5fzlOf9SZfpr8
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # use validate/none in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181

jwt:
  secret: mySuperSecretKeyForJwtTokenGeneration123456
  expiration: 86400000